
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
    "name": "Tyler",
    "dateOfBirth": "05/09/1995",
    "ssn": "asdfwe24-v324sdvasd",
    "gender": "male",
    "occupation": "dancer"
}


###

GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667
